### ISSUE TITLE
Adding support for extended mode

### ISSUE THREAD

**Issue by laszlocsontos** [spring-projects/spring-social-twitter#120]
On September 26, 2017, Twitter announced an experiment enabling Tweets with more characters. These Tweets are encoded in JSON as an extended Tweet.

There are two modes for rendering Tweet JSON objects to API clients: **compatibility** mode and **extended** mode. Compatibility mode is the default mode for the standard REST and Streaming APIs and Gnip products, and is designed to not break existing clients.

Now the **compatibility** mode is the default where `text` field is truncated to 140, `truncated` field is `true` and `entities` only include those which are in the available 140 text range.

Example:
> Hey #jvmcon! Save 40% on #JVM, #java9, #modules, #springboot, #scala, and other books and videos with code ctwjvmco… https://twitter.com/i/web/status/958339020542525441 …

Tweet is truncated at the 140th character and a link is included at the end in order to be able to see the Tweet in its full length.

In **extended** mode Tweet payload contains all information to render Tweets that contain more than 140 characters when `tweet_mode=extended` parameter is added to any REST endpoint. In this case `full_text` replaces `text`, `truncated` field is `false` and `display_text_range` delineates different sections of body for mentions/tweets/entities.

Example:
> Hey #jvmcon! Save 40% on #JVM, #java9, #modules, #springboot, #scala, and other books and videos with code ctwjvmcon18 at http://manning.com  #manningbooks

In the future, an additional announcement will be made when the time is right to make a change for the rendering mode to default to extended mode.

I'm working on a Social Media automation app and with the current release of `spring-social-twitter`, **extended** Tweets cannot be processed properly.

I'd gladly contribute support for extended tweets and get rid of my nasty workarounds.
************
Reference: [Tweet Updates](https://developer.twitter.com/en/docs/tweets/tweet-updates)

**Comment by mlopeza** [comment]
I decided to start working on this as I recently started using this project and saw that some of my tweets were truncated. I don't expect the change to be too intrusive as this is just support for extra attributes. Not sure if someone else is actually working on this that would like to contribute what they have.

**Comment by laszlocsontos** [comment]
Hey @mlopeza, I wanted to contribute extended tweet support too. However, I decided to wait a little instead until I get feedback from @habuma (dev lead of Spring Social) if he has got bandwidth to review it.

**Comment by mlopeza** [comment]
@laszlocsontos , independently of the bandwidth of the maintainer the PR can be created and discussed. I made it work, but I still need to rework some code  and add tests, for now I just tested the streaming api as that's my main use case, but once I finish with the tests for that part I'll check what kind of changes do the other endpoints need, as far as I know a support for a flag in the configuration of connection might be needed.

If you are interested on taking a look and make some suggestions you are welcome to do so https://github.com/mlopeza/spring-social-twitter/tree/extended_tweet

**Comment by laszlocsontos** [comment]
Sure, we can discuss it. :+1: 

I looked into your branch and I'm wondering, wouldn't it be better to incorporate changes related to extended tweets into `org.springframework.social.twitter.api.Tweet` directly?

As an API consumer, I'd prefer to have transparent API and just use `getText()`. Anothers methods like `isExtended()/isTruncated()` could denote if the tweet is extended or if it was an extended tweet, but it got truncated.

What do you think?

**Comment by sandislonjsak** [comment]
Hi guys, is someone still working on this issue?

**Comment by laszlocsontos** [comment]
Spring Social is EOL now: https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement
